# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190618_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['priority', 'id'], 'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['id'], 'verbose_name': '权限表', 'verbose_name_plural': '权限表'},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='priority',
        ),
        migrations.AddField(
            model_name='menu',
            name='priority',
            field=models.IntegerField(blank=True, help_text='菜单的显示顺序，优先级越小显示越靠前', null=True, verbose_name='显示优先级'),
        ),
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='二级菜单图标'),
        ),
    ]
