# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20190618_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Identity',
            new_name='Role',
        ),
    ]
